'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import { InputComponent as InputComponentElement, defineCustomElement as defineInputComponent } from "stencil-library/dist/components/input-component.js";
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "stencil-library/dist/components/my-component.js";
import { TestComponent as TestComponentElement, defineCustomElement as defineTestComponent } from "stencil-library/dist/components/test-component.js";
import { TooltipComponent as TooltipComponentElement, defineCustomElement as defineTooltipComponent } from "stencil-library/dist/components/tooltip-component.js";

export type InputComponentEvents = NonNullable<unknown>;

export const InputComponent: StencilReactComponent<InputComponentElement, InputComponentEvents> = /*@__PURE__*/ createComponent<InputComponentElement, InputComponentEvents>({
    tagName: 'input-component',
    elementClass: InputComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as InputComponentEvents,
    defineCustomElement: defineInputComponent
});

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent
});

export type TestComponentEvents = NonNullable<unknown>;

export const TestComponent: StencilReactComponent<TestComponentElement, TestComponentEvents> = /*@__PURE__*/ createComponent<TestComponentElement, TestComponentEvents>({
    tagName: 'test-component',
    elementClass: TestComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as TestComponentEvents,
    defineCustomElement: defineTestComponent
});

export type TooltipComponentEvents = NonNullable<unknown>;

export const TooltipComponent: StencilReactComponent<TooltipComponentElement, TooltipComponentEvents> = /*@__PURE__*/ createComponent<TooltipComponentElement, TooltipComponentEvents>({
    tagName: 'tooltip-component',
    elementClass: TooltipComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as TooltipComponentEvents,
    defineCustomElement: defineTooltipComponent
});
