export const spacings = {
  "bpop-spacing-xxxxxs": "0.0625rem",
  "bpop-spacing-xxxxs": "0.125rem",
  "bpop-spacing-xxxs": "0.25rem",
  "bpop-spacing-xxs": "0.375rem",
  "bpop-spacing-xs": "0.5rem",
  "bpop-spacing-2xs": "0.625rem",
  "bpop-spacing-s": "0.75rem",
  "bpop-spacing-sm": "1rem",
  "bpop-spacing-2sm": "1.25rem",
  "bpop-spacing-md": "1.5rem",
  "bpop-spacing-lg": "2rem",
  "bpop-spacing-xl": "2.5rem",
  "bpop-spacing-2xl": "3rem",
  "bpop-spacing-3xl": "3.5rem",
  "bpop-spacing-4xl": "4rem",
  "bpop-spacing-5xl": "4.5rem",
  "bpop-spacing-6xl": "5rem",
};
