/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InputComponent {
        "class": string;
        "name": string;
        "text_error": string;
        "text_label": string;
        /**
          * @default 'text'
         */
        "type": string;
        "value": string;
    }
    interface LoaderComponent {
        /**
          * @default 'normal'
         */
        "animationDirection": 'normal' | 'reverse' | 'alternate' | 'alternate-reverse';
        /**
          * @default 2
         */
        "animationDuration": number;
        /**
          * @default 'ease-in-out'
         */
        "animationEasing": string;
        /**
          * @default 'infinite'
         */
        "animationIterations": number | string | 'infinite';
        /**
          * @default '#3498db'
         */
        "color": string;
        /**
          * @default false
         */
        "debug": boolean;
        /**
          * @default 1
         */
        "opacityFrom": number;
        /**
          * @default 1
         */
        "opacityTo": number;
        /**
          * @default 0
         */
        "rotateFrom": number;
        /**
          * @default 360
         */
        "rotateTo": number;
        /**
          * @default 1
         */
        "scaleFrom": number;
        /**
          * @default 1.2
         */
        "scaleTo": number;
        /**
          * @default true
         */
        "showText": boolean;
        /**
          * @default 50
         */
        "size": number;
        /**
          * @default 1
         */
        "speed": number;
        /**
          * @default 'rotate'
         */
        "svgAnimation": 'rotate' | 'scale' | 'pulse-scale' | 'bounce' | 'translate' | 'custom' | 'none';
        "svgPath": string;
        /**
          * @default 50
         */
        "svgSize": number;
        /**
          * @default 'Cargando...'
         */
        "text": string;
        "textColor": string;
        /**
          * @default 'ease-in-out'
         */
        "transition": string;
        /**
          * @default 0
         */
        "translateX": number;
        /**
          * @default 0
         */
        "translateY": number;
        /**
          * @default 'spinner'
         */
        "type": 'spinner' | 'dots' | 'pulse' | 'bars' | 'ring' | 'dual-ring' | 'ellipsis' | 'ripple' | 'svg';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TestComponent {
        "text_button": string;
    }
}
declare global {
    interface HTMLInputComponentElement extends Components.InputComponent, HTMLStencilElement {
    }
    var HTMLInputComponentElement: {
        prototype: HTMLInputComponentElement;
        new (): HTMLInputComponentElement;
    };
    interface HTMLLoaderComponentElement extends Components.LoaderComponent, HTMLStencilElement {
    }
    var HTMLLoaderComponentElement: {
        prototype: HTMLLoaderComponentElement;
        new (): HTMLLoaderComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTestComponentElement extends Components.TestComponent, HTMLStencilElement {
    }
    var HTMLTestComponentElement: {
        prototype: HTMLTestComponentElement;
        new (): HTMLTestComponentElement;
    };
    interface HTMLElementTagNameMap {
        "input-component": HTMLInputComponentElement;
        "loader-component": HTMLLoaderComponentElement;
        "my-component": HTMLMyComponentElement;
        "test-component": HTMLTestComponentElement;
    }
}
declare namespace LocalJSX {
    interface InputComponent {
        "class"?: string;
        "name"?: string;
        "text_error"?: string;
        "text_label"?: string;
        /**
          * @default 'text'
         */
        "type"?: string;
        "value"?: string;
    }
    interface LoaderComponent {
        /**
          * @default 'normal'
         */
        "animationDirection"?: 'normal' | 'reverse' | 'alternate' | 'alternate-reverse';
        /**
          * @default 2
         */
        "animationDuration"?: number;
        /**
          * @default 'ease-in-out'
         */
        "animationEasing"?: string;
        /**
          * @default 'infinite'
         */
        "animationIterations"?: number | string | 'infinite';
        /**
          * @default '#3498db'
         */
        "color"?: string;
        /**
          * @default false
         */
        "debug"?: boolean;
        /**
          * @default 1
         */
        "opacityFrom"?: number;
        /**
          * @default 1
         */
        "opacityTo"?: number;
        /**
          * @default 0
         */
        "rotateFrom"?: number;
        /**
          * @default 360
         */
        "rotateTo"?: number;
        /**
          * @default 1
         */
        "scaleFrom"?: number;
        /**
          * @default 1.2
         */
        "scaleTo"?: number;
        /**
          * @default true
         */
        "showText"?: boolean;
        /**
          * @default 50
         */
        "size"?: number;
        /**
          * @default 1
         */
        "speed"?: number;
        /**
          * @default 'rotate'
         */
        "svgAnimation"?: 'rotate' | 'scale' | 'pulse-scale' | 'bounce' | 'translate' | 'custom' | 'none';
        "svgPath"?: string;
        /**
          * @default 50
         */
        "svgSize"?: number;
        /**
          * @default 'Cargando...'
         */
        "text"?: string;
        "textColor"?: string;
        /**
          * @default 'ease-in-out'
         */
        "transition"?: string;
        /**
          * @default 0
         */
        "translateX"?: number;
        /**
          * @default 0
         */
        "translateY"?: number;
        /**
          * @default 'spinner'
         */
        "type"?: 'spinner' | 'dots' | 'pulse' | 'bars' | 'ring' | 'dual-ring' | 'ellipsis' | 'ripple' | 'svg';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TestComponent {
        "text_button"?: string;
    }
    interface IntrinsicElements {
        "input-component": InputComponent;
        "loader-component": LoaderComponent;
        "my-component": MyComponent;
        "test-component": TestComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "input-component": LocalJSX.InputComponent & JSXBase.HTMLAttributes<HTMLInputComponentElement>;
            "loader-component": LocalJSX.LoaderComponent & JSXBase.HTMLAttributes<HTMLLoaderComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "test-component": LocalJSX.TestComponent & JSXBase.HTMLAttributes<HTMLTestComponentElement>;
        }
    }
}
