/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TooltipAlignment } from "./components/tooltip-component/tooltip-component.interface";
export { TooltipAlignment } from "./components/tooltip-component/tooltip-component.interface";
export namespace Components {
    interface AppCarousel {
        /**
          * @default '400px'
         */
        "height": string;
        /**
          * @default []
         */
        "images": string[];
        /**
          * @default 3000
         */
        "interval": number;
        /**
          * @default 'contain'
         */
        "objectFit": 'cover' | 'contain';
        /**
          * @default []
         */
        "texts"?: string[];
        /**
          * @default 'slider'
         */
        "variant": 'slider' | 'dots' | 'mixed';
        /**
          * @default '100%'
         */
        "width": string;
    }
    interface InputComponent {
        "class": string;
        "name": string;
        "text_error": string;
        "text_label": string;
        /**
          * @default 'text'
         */
        "type": string;
    }
    interface ModalComponent {
        /**
          * @default ''
         */
        "height": string;
        /**
          * @default false
         */
        "is_open": boolean;
        /**
          * @default ''
         */
        "title": string;
        /**
          * @default ''
         */
        "width": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface NdText {
        /**
          * @default 'left'
         */
        "align": 'left' | 'center' | 'right' | 'justify';
        "color"?: string;
        "customClass"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        "href"?: string;
        "htmlFor"?: string;
        "maxLines"?: number;
        /**
          * @default '_self'
         */
        "target"?: '_blank' | '_self' | '_parent' | '_top';
        /**
          * @default false
         */
        "truncate": boolean;
        /**
          * @default 'p'
         */
        "variant": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'label' | 'link' | 'error' | 'caption' | 'small';
        /**
          * @default 'normal'
         */
        "weight": 'light' | 'normal' | 'medium' | 'semibold' | 'bold';
    }
    interface TestComponent {
        "text_button": string;
    }
    interface TooltipComponent {
        /**
          * @default TOOLTIP_ALIGNMENT.TOP
         */
        "alignment": TooltipAlignment;
        "text": string;
    }
}
export interface CheckComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCheckComponentElement;
}
export interface InputComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLInputComponentElement;
}
export interface ModalComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModalComponentElement;
}
export interface SelectComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSelectComponentElement;
}
declare global {
    interface HTMLAppCarouselElement extends Components.AppCarousel, HTMLStencilElement {
    }
    var HTMLAppCarouselElement: {
        prototype: HTMLAppCarouselElement;
        new (): HTMLAppCarouselElement;
    };
    interface HTMLInputComponentElement extends Components.InputComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLInputComponentElementEventMap>(type: K, listener: (this: HTMLInputComponentElement, ev: InputComponentCustomEvent<HTMLInputComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLInputComponentElementEventMap>(type: K, listener: (this: HTMLInputComponentElement, ev: InputComponentCustomEvent<HTMLInputComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLInputComponentElement: {
        prototype: HTMLInputComponentElement;
        new (): HTMLInputComponentElement;
    };
    interface HTMLModalComponentElementEventMap {
        "modalClosed": void;
    }
    interface HTMLModalComponentElement extends Components.ModalComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLModalComponentElementEventMap>(type: K, listener: (this: HTMLModalComponentElement, ev: ModalComponentCustomEvent<HTMLModalComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLModalComponentElementEventMap>(type: K, listener: (this: HTMLModalComponentElement, ev: ModalComponentCustomEvent<HTMLModalComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLModalComponentElement: {
        prototype: HTMLModalComponentElement;
        new (): HTMLModalComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLNdTextElement extends Components.NdText, HTMLStencilElement {
    }
    var HTMLNdTextElement: {
        prototype: HTMLNdTextElement;
        new (): HTMLNdTextElement;
    };
    interface HTMLTestComponentElement extends Components.TestComponent, HTMLStencilElement {
    }
    var HTMLTestComponentElement: {
        prototype: HTMLTestComponentElement;
        new (): HTMLTestComponentElement;
    };
    interface HTMLTooltipComponentElement extends Components.TooltipComponent, HTMLStencilElement {
    }
    var HTMLTooltipComponentElement: {
        prototype: HTMLTooltipComponentElement;
        new (): HTMLTooltipComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-carousel": HTMLAppCarouselElement;
        "input-component": HTMLInputComponentElement;
        "modal-component": HTMLModalComponentElement;
        "my-component": HTMLMyComponentElement;
        "nd-text": HTMLNdTextElement;
        "test-component": HTMLTestComponentElement;
        "tooltip-component": HTMLTooltipComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppCarousel {
        /**
          * @default '400px'
         */
        "height"?: string;
        /**
          * @default []
         */
        "images"?: string[];
        /**
          * @default 3000
         */
        "interval"?: number;
        /**
          * @default 'contain'
         */
        "objectFit"?: 'cover' | 'contain';
        /**
          * @default []
         */
        "texts"?: string[];
        /**
          * @default 'slider'
         */
        "variant"?: 'slider' | 'dots' | 'mixed';
        /**
          * @default '100%'
         */
        "width"?: string;
    }
    interface InputComponent {
        "class"?: string;
        "name"?: string;
        "onInputTarget"?: (event: InputComponentCustomEvent<{ name: string; value: string }>) => void;
        "text_error"?: string;
        "text_label"?: string;
        /**
          * @default 'text'
         */
        "type"?: string;
    }
    interface ModalComponent {
        /**
          * @default ''
         */
        "height"?: string;
        /**
          * @default false
         */
        "is_open"?: boolean;
        "onModalClosed"?: (event: ModalComponentCustomEvent<void>) => void;
        /**
          * @default ''
         */
        "title"?: string;
        /**
          * @default ''
         */
        "width"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface NdText {
        /**
          * @default 'left'
         */
        "align"?: 'left' | 'center' | 'right' | 'justify';
        "color"?: string;
        "customClass"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "href"?: string;
        "htmlFor"?: string;
        "maxLines"?: number;
        /**
          * @default '_self'
         */
        "target"?: '_blank' | '_self' | '_parent' | '_top';
        /**
          * @default false
         */
        "truncate"?: boolean;
        /**
          * @default 'p'
         */
        "variant"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'label' | 'link' | 'error' | 'caption' | 'small';
        /**
          * @default 'normal'
         */
        "weight"?: 'light' | 'normal' | 'medium' | 'semibold' | 'bold';
    }
    interface TestComponent {
        "text_button"?: string;
    }
    interface TooltipComponent {
        /**
          * @default TOOLTIP_ALIGNMENT.TOP
         */
        "alignment"?: TooltipAlignment;
        "text"?: string;
    }
    interface IntrinsicElements {
        "app-carousel": AppCarousel;
        "input-component": InputComponent;
        "modal-component": ModalComponent;
        "my-component": MyComponent;
        "nd-text": NdText;
        "test-component": TestComponent;
        "tooltip-component": TooltipComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-carousel": LocalJSX.AppCarousel & JSXBase.HTMLAttributes<HTMLAppCarouselElement>;
            "input-component": LocalJSX.InputComponent & JSXBase.HTMLAttributes<HTMLInputComponentElement>;
            "modal-component": LocalJSX.ModalComponent & JSXBase.HTMLAttributes<HTMLModalComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "nd-text": LocalJSX.NdText & JSXBase.HTMLAttributes<HTMLNdTextElement>;
            "test-component": LocalJSX.TestComponent & JSXBase.HTMLAttributes<HTMLTestComponentElement>;
            "tooltip-component": LocalJSX.TooltipComponent & JSXBase.HTMLAttributes<HTMLTooltipComponentElement>;
        }
    }
}
